language: c
script: bash -e .travis-ci.sh
env:
  global:
    secure: VxIqnPGObq63Rbd+ld5LyyHY+UOIdwlQ1y8HZufvO3QaIhEng5L3K2DBUj+gsxeXpRaIYiaW8zSSDEDxp5l41lIoqVDR4p5I25CSgChOTH8wSd8ZAiph5b2H4KE7AuhXivac9QPI4SVX9B702GPzFfBLcm6q18w4q4/NVv1VRQA="
  matrix:
    - OCAML_VERSION=4.01.0
    - OCAML_VERSION=4.01.0 EXTRA_DEPENDS="cmdliner lablgtk cairo2"
    - OCAML_VERSION=4.01.0 EXTRA_DEPENDS="tyxml js_of_ocaml"
    - OCAML_VERSION=4.01.0 EXTRA_DEPENDS="cfstream gen batteries core_kernel" TEST="-t"
    - OCAML_VERSION=4.02.1 EXTRA_DEPENDS="cfstream gen batteries core_kernel" TEST="-t"
    - OCAML_VERSION=4.01.0 EXTRA_DEPENDS="cmdliner lablgtk cairo2 tyxml js_of_ocaml gen cfstream batteries core_kernel" DOC="true"
